// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ivankorhner/polling-app/internal/ent/poll"
	"github.com/ivankorhner/polling-app/internal/ent/polloption"
	"github.com/ivankorhner/polling-app/internal/ent/schema"
	"github.com/ivankorhner/polling-app/internal/ent/user"
	"github.com/ivankorhner/polling-app/internal/ent/vote"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pollFields := schema.Poll{}.Fields()
	_ = pollFields
	// pollDescTitle is the schema descriptor for title field.
	pollDescTitle := pollFields[2].Descriptor()
	// poll.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	poll.TitleValidator = pollDescTitle.Validators[0].(func(string) error)
	// pollDescCreatedAt is the schema descriptor for created_at field.
	pollDescCreatedAt := pollFields[3].Descriptor()
	// poll.DefaultCreatedAt holds the default value on creation for the created_at field.
	poll.DefaultCreatedAt = pollDescCreatedAt.Default.(func() time.Time)
	polloptionFields := schema.PollOption{}.Fields()
	_ = polloptionFields
	// polloptionDescText is the schema descriptor for text field.
	polloptionDescText := polloptionFields[2].Descriptor()
	// polloption.TextValidator is a validator for the "text" field. It is called by the builders before save.
	polloption.TextValidator = polloptionDescText.Validators[0].(func(string) error)
	// polloptionDescVoteCount is the schema descriptor for vote_count field.
	polloptionDescVoteCount := polloptionFields[3].Descriptor()
	// polloption.DefaultVoteCount holds the default value on creation for the vote_count field.
	polloption.DefaultVoteCount = polloptionDescVoteCount.Default.(int)
	// polloption.VoteCountValidator is a validator for the "vote_count" field. It is called by the builders before save.
	polloption.VoteCountValidator = polloptionDescVoteCount.Validators[0].(func(int) error)
	// polloptionDescCreatedAt is the schema descriptor for created_at field.
	polloptionDescCreatedAt := polloptionFields[4].Descriptor()
	// polloption.DefaultCreatedAt holds the default value on creation for the created_at field.
	polloption.DefaultCreatedAt = polloptionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	voteFields := schema.Vote{}.Fields()
	_ = voteFields
	// voteDescCreatedAt is the schema descriptor for created_at field.
	voteDescCreatedAt := voteFields[4].Descriptor()
	// vote.DefaultCreatedAt holds the default value on creation for the created_at field.
	vote.DefaultCreatedAt = voteDescCreatedAt.Default.(func() time.Time)
}
