-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "username" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "polls" table
CREATE TABLE "polls" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "owner_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "polls_users_polls" FOREIGN KEY ("owner_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "poll_options" table
CREATE TABLE "poll_options" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "text" character varying NOT NULL,
  "vote_count" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "poll_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "poll_options_polls_options" FOREIGN KEY ("poll_id") REFERENCES "polls" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "votes" table
CREATE TABLE "votes" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "poll_id" bigint NOT NULL,
  "option_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "votes_poll_options_votes" FOREIGN KEY ("option_id") REFERENCES "poll_options" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "votes_polls_votes" FOREIGN KEY ("poll_id") REFERENCES "polls" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "votes_users_votes" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "vote_user_id_poll_id" to table: "votes"
CREATE UNIQUE INDEX "vote_user_id_poll_id" ON "votes" ("user_id", "poll_id");
